[params]
  # Basic Colors (Engineering Style)
  background_color_class = "bg-near-black" # Dark professional look
  text_color_class = "text-white"
  
    description = "Junior ECE Student | Focusing on Digital Systems and Control Theory."
  # This text appears on your homepage as the introduction
  recent_posts_number = 1

  # Fonts: Ananke uses System Fonts by default for speed
  # You can customize these if you use an asset folder, but system-sans is standard
  body_classes = "avenir next, sans-serif" 
  
  # Sidebar/Menu Configuration
  main_sections = ["posts", "projects"]

  [[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 10