baseURL = "https://engineering-portfolio.pages.dev/"
languageCode = "en-us"
title = "Jay's Personal Engineering Portfolio"
theme = "ananke"

[params]
  # Basic Colors (Engineering Style)
  background_color_class = "bg-near-black"
  text_color_class = "text-white"
  
  # This appears as your homepage introduction
  description = "Junior ECE Student | Focusing on Digital Systems and Control Theory."
  recent_posts_number = 1

  # Fonts
  body_classes = "avenir next, sans-serif" 
  
  # Tells Hugo which folders to show on the homepage
  main_sections = ["posts", "projects"]

# Menu configuration (Must be outside of [params])
[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 10